name: Context example

on: ['push']

jobs:
  my-context:
    runs-on: ubuntu-latest
    steps: 
      - name: "My step"
        run: echo "Zdarova! $MY_ACTION"
        env: 
          MY_CATION: ${{ github.action }}  
