name: Context example

on: ['push']

jobs:
  my-context:
    runs-on: ubuntu-latest
    steps: 
      - name: "My step"
        run: |
          echo "Zdarova! $MY_ACTION"
          echo "my actpor is $MY_ACTOR"
        env: 
          MY_ACTION: ${{ github.action }}  
          MY_ACTOR: ${{ github.actor }}
 