name: "Running some jobs"

on: ['push']

jobs:
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: second step 
        run: echo "second job is complited"
  job1:
    runs-on: ubuntu-latest
    steps: 
      - name: fiest step 
        run: echo "first job is complited"
        
     